#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.
if [ -x $HOME/.config/xrandr/dual_monitor.sh ];then
    $HOME/.config/xrandr/dual_monitor.sh
fi


$HOME/.config/polybar/launch.sh

bspc monitor DP-0 -d I II III IV
bspc monitor HDMI-0 -d V VI VII VIII
bspc monitor HDMI-0 -s DP-0

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
